server:
  port: 8082
  servlet:
    context-path: /ventas
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2
datasource:
  ventasapp:
    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    initialization-mode: embedded
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
